from .admin_order_details import AdminOrderDetailsView
from .cart import CartPageView
from .home import HomePageView
from .item import ItemUpdateView
from .order_details import OrderDetailsView
from .view import SignUpView
from .logout import CustomLogoutView
from .login import CustomLoginView
from .category import CategoryUpdate