# Generated by Django 4.2.8 on 2023-12-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("resturant", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="orderIems", new_name="order_items"
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
