# Generated by Django 4.2.8 on 2024-01-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("resturant", "0003_alter_order_user")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        )
    ]
