# Generated by Django 4.2.8 on 2024-01-03 14:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resturant", "0004_order_order_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="profile image"
            ),
        ),
    ]
