# Generated by Django 4.2.8 on 2024-01-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("resturant", "0005_alter_item_photo")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="action_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
