# Generated by Django 4.2.8 on 2024-01-05 11:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("resturant", "0006_order_action_timestamp")]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="https://res.cloudinary.com/dqxbl0sux/image/upload/v1704364081/wqklk7lsghidaehjkrq0.png",
                max_length=255,
                null=True,
                verbose_name="profile image",
            ),
        )
    ]
